"""Add tickets table

Revision ID: 90cef20192b5
Revises: 31f4f1b60881
Create Date: 2025-10-31 01:03:51.679035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90cef20192b5'
down_revision = '31f4f1b60881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
